version: 1.0.{build}

pull_requests:

  do_not_increment_build_number: true

configuration: Release

platform:
- x86
- x64
- ARM

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

environment:

  certPW:
    secure: 6yNH6WecxEMjKhrUVjhWoBw60rnjOxc4iZovDbDA9qiNVE1poPnDt+fQtIqeU3ye

install:

- ps: >-

    $psw = ConvertTo-SecureString $env:certPW -AsPlainText -Force

    Import-PfxCertificate -FilePath .\NewTelegramBot\NewTelegramBot_TemporaryKey.pfx -CertStoreLocation cert:\CurrentUser\My -Password $psw

before_build:

- cmd: nuget restore

build:

  parallel: true

  verbosity: minimal

deploy: off